import type { Metadata } from "next";
import { Outfit, Sora } from "next/font/google";
import "./globals.css";

// Global brand fonts
const outfit = Outfit({ variable: "--font-outfit", subsets: ["latin"], weight: ["400","500","600","700"] });
const sora = Sora({ variable: "--font-heading", subsets: ["latin"], weight: ["500","600","700","800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${sora.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
